# -*- coding: utf-8 -*-
"""Viral caption architect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPkUT3Z6NbVBMFeHfMMlBM_t2jwRfF6I
"""

from google.colab import userdata
import streamlit as st

# 1. Get the key from your Colab Secrets (the Key icon on the left)
try:
    MY_GEMINI_KEY = userdata.get('GEMINI_KEY')
except:
    st.error("Make sure you added 'GEMINI_KEY' to the Colab Secrets (Key icon) and enabled access!")

# 1. Update the app file
with open('app.py', 'w') as f:
    f.write(f'''
import streamlit as st
import requests
from bs4 import BeautifulSoup
import google.generativeai as genai

# Configuration - Using the key we pulled from Colab
genai.configure(api_key="{MY_GEMINI_KEY}")
model = genai.GenerativeModel('gemini-3-flash-preview')

def fetch_blog_content(url):
    try:
        headers = {{'User-Agent': 'Mozilla/5.0'}}
        response = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(response.content, 'html.parser')
        title = soup.find('h1').text if soup.find('h1') else "Blog Post"
        paragraphs = soup.find_all('p')
        text = " ".join([p.text for p in paragraphs[:15]])
        return title, text
    except Exception as e:
        return None, str(e)

def generate_caption(title, content, platform):
    prompts = {{
        "LinkedIn": f"Write a professional LinkedIn post for: {{title}}. Context: {{content}}. Structure: Hook, Value points, and CTA.",
        "Instagram": f"Write an engaging Instagram caption for: {{title}}. Context: {{content}}. Use emojis and 3 hashtags.",
        "YouTube": f"Write a YouTube description and 3 click-worthy titles for: {{title}}. Context: {{content}}."
    }}
    instruction = "You are a viral social media manager. Make the reader want to click the link."
    response = model.generate_content(f"{{instruction}} {{prompts[platform]}}")
    return response.text

# --- UI ---
st.set_page_config(page_title="Viral Caption Architect", page_icon="✍️")
st.title("✍️ Viral Caption Architect")
blog_url = st.text_input("Paste Blog URL here:")
platform = st.selectbox("Select Platform", ["LinkedIn", "Instagram", "YouTube"])

if st.button("Generate Content"):
    if blog_url:
        with st.spinner('Thinking with Gemini 3...'):
            title, content = fetch_blog_content(blog_url)
            if title:
                caption = generate_caption(title, content, platform)
                st.subheader(f"🚀 Your {{platform}} Post")
                st.write(caption)
                st.divider()
                st.info(f"**Source Link:** {{blog_url}}")
            else:
                st.error("Scrape failed. Check the URL.")
    else:
        st.warning("Enter a URL.")
''')

print("Success: app.py updated and fixed!")

import sys
import streamlit as st
import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
e

from pyngrok import ngrok
import subprocess

# 1. Kill any existing tunnels
ngrok.kill()

# 2. Authenticate
ngrok.set_auth_token("3COabclODZIfsVIHMfsD0huEmq3_2zAR233v9dwf6gkQLFHn8")

# 3. Start Streamlit in the background
subprocess.Popen(["streamlit", "run", "app.py"])

# 4. Open the tunnel
public_url = ngrok.connect(8501)
print(f"✅ Your App is Live at: {public_url}")

with open('requirements.txt', 'w') as f:
    f.write('''
streamlit
requests
beautifulsoup4
google-generativeai
''')
